### ISSUE TITLE
Questions on how to start

### ISSUE THREAD

**Issue by karmen-chan** [jkirsch/senser#1]
Hi jkirsch,

I'm learning how to combine OpenCV with Flink by myself, and find your project "senser" is quite a good study material for me. I have tried to run your project on my own PC, however, problems have been met. 

After running ./mvnw spring-boot:run, neither videos nor images were showed on localhost:8080 or localhost:8080/images. May I ask for your kind help to start with it? @jkirsch 

Looking forward to your kind reply. = )

Regards.
Karmen

**Comment by karmen-chan** [comment]
Update.

After updating the version of jar, now I can run it on my own PC (mac os) with eclipse. However, I still cannot run it on linux (Ubuntu) with error: ### **Error: Error: Cannot find where you keep your Bower packages**. Do you have any idea?

**Comment by jkirsch** [comment]
Did you run

    ./mvnw compile -P generate-frontend

Before you started the project?
It currently defaults to displaying the live german television [URL][1]
Which takes a couple seconds to initialize.
You will see a new window popup which shows the video stream.
The web urls are just for debugging and inspection.

Just a note: if you want to process the images with flink in this way you have to be aware that the used java/openCV bindings are not thread safe.

[1]: https://github.com/jkirsch/senser/blob/master/src/main/resources/application.properties#L16

**Comment by karmen-chan** [comment]
Thanks for your reply! I can run the project successfully on PC with video popping up. However, when running it on Ubuntu, the web urls can be opened, but no video pops up. Of course, no result was shown on the web page as well. I think maybe it is a problem with using JMS in Ubuntu? (Sorry, I am not familiar with JAVA.) To make it work on Ubuntu, maybe I should code to realize another method presenting the video?

**Comment by jkirsch** [comment]
Well, if you just want to learn, you have the PC (windows?) and mac version working - so no reason for ubuntu. 
Also ubuntu has many different version, there is probably an inconsistency with the libraries you have installed - wonder if there is an error message present in the logs. Or maybe an outdated java version, or libc.
As this is just a demo project, I'm afraid I cant help you more here - it's probably best to start implementing whatever you want yourself and use this project only as a bootstrap in parts.

**Comment by karmen-chan** [comment]
Yes, the project is just a good learning material, that helps me understand how to use OpenCV with Flink in JAVA, like what I have said at the beginning. Since I have already run it on Mac os, I will study further by reading the codes in details.

As for running on Ubuntu, I just want to verify whether OpenCV with Flink 
can be implemented successfully. The answer may be yes. I will try to prove it in the following days. 

Thanks for your kind reply! = )
