### ISSUE TITLE
Request for Freepal Dataset, Sincerely

### ISSUE THREAD

**Issue by remonly** [jkirsch/senser#2]
Dear Dr. Krischnick, 

I'm a post-graduate student from Nanjing University, China. My interest mainly focus on QA, and we are now working on some analysis of Noun Phrases in questions. 

I've read your paper "Freepal: A Large Collection of Deep Lexico-Syntactic Patterns for Relation Extraction", and found it really helpful for our work. However, I found that your link of dataset on "https://free-pal.appspot.com/#contact" is not work, and your email address is not work as well. And I'm writing to request the dataset of your work as follows: Large datas, and Non lemmatized. And of course I'll cite your paper in the related publication.

I know it's not appropriate to communicate with you over github, but I can't find your current email address. If you feel offended, I'll delete this letter, of course.

I would appreciate it if you can provide these datasets to me, and I'm looking forward to hearing from you. My email address is jjyu0429@outlook.com. Thank you for your time. 

Best Regards，
Jiajie Yu

**Comment by jkirsch** [comment]
Thanks for reaching out

You find the large dataset here

https://www.dropbox.com/s/fd05tkoeutzwluo/freepal-dataset.json.bz2?dl=0

**Comment by remonly** [comment]
Thank you so much for your kindness help again.

**Comment by jkirsch** [comment]
No Problem,

You also find the no-lemma-version here

https://www.dropbox.com/s/i01ys6zgczmy1za/freepal-dataset-nolemma.json.bz2?dl=0
